### PR TITLE
Purge lies in ResponseSetPrepopulation#populators_for docs

### PR DESCRIPTION
**Pull request by hannahwhy**
See commit message.

### CODE REVIEW

**Comment by rsutphin** [comment]
I don't think that RECOMMENDED really captures the desired behavior. It's more like, if there is going be a `Participant` associated with the response set, it SHOULD be set before prepopulation occurs, otherwise the prepopulators might miss something. Ditto for `Instrument` and any other association. The associations might not be set, but that should only be because they will never be set for that response set.

**Comment by hannahwhy** [comment]
How about this:

```
If a ResponseSet has a Participant, Instrument, or other operational data
associated with it, those associations SHOULD be set before running
prepopulators on that ResponseSet.  If they are not present before
prepopulation occurs, the relevant operational data will not be reflected in
the ResponseSet's responses.

In Cases, prepopulation tends to occur immediately after calling
#populators_for; therefore, you SHOULD set up all associations before calling
#populators_for.

@see ResponseSet#prepopulate
```

**Comment by pfriedman** [comment]
The updated comments look accurate to me.

**Comment by hannahwhy** [comment]
I didn't like my first draft, so I pushed another one.  This one moves documentation around to what are IMO better places.

**Pull request merged**
