### PR TITLE
Regenerate pg_dump files. #4143, #4149, #4159

### PR DESCRIPTION
**Pull request by jefflunt**
- Ran `rake mdes:code_lists_all`
- New versions of pg_dump files
- YAML files were unaffected
- I believe this to be the root of the issue for each of #4143, #4149
  and #4159

As noted in https://code.bioinformatics.northwestern.edu/issues/issues/show/4143 I may very well be missing something here.

### CODE REVIEW

**Comment by jefflunt** [comment]
Hold off for now - there is a deeper problem brought up in scrum regarding test failures that should be addressed before this pull request is seriously considered.

**Comment by rsutphin** [comment]
There are several problems with the CI build right now. The one I see that could be related to this is in the specs for `ResponseSetPrepopulation::PbsParticipantVerification`. Those specs attempt to swap code lists to the MDES 3.2 ones and fail because pg_restore can't read the dumpfile:

```
ResponseSetPrepopulation::PbsParticipantVerification
  for prepopulated P_TYPE 15 response in part two of M3.2
    prepopulated_is_p_type_fifteen
pg_restore: [archiver] unexpected end of file
      should be TRUE if participant is of p_code 15 type (FAILED - 1)
pg_restore: [archiver] unexpected end of file
      should be FALSE if participant is not of p_code 15 type (FAILED - 2)
pg_restore: [archiver] unexpected end of file
      should be TRUE if participant is a child and participant's mother has p_code 15 (FAILED - 3)
pg_restore: [archiver] unexpected end of file
      should be FALSE if participant is a child and participant's mother is not of p_code 15 (FAILED - 4)
```

These fail for me locally in the same way, so I don't think it's a CI problem specifically. I tried running this spec from the branch for this PR and pg_restore did not have a problem. The specs still failed, but for a different reason:

```
ResponseSetPrepopulation::PbsParticipantVerification
  for prepopulated P_TYPE 15 response in part two of M3.2
    prepopulated_is_p_type_fifteen
      should be TRUE if participant is of p_code 15 type (FAILED - 1)
      should be FALSE if participant is not of p_code 15 type (FAILED - 2)
      should be TRUE if participant is a child and participant's mother has p_code 15 (FAILED - 3)
      should be FALSE if participant is a child and participant's mother is not of p_code 15 (FAILED - 4)

Failures:

  1) ResponseSetPrepopulation::PbsParticipantVerification for prepopulated P_TYPE 15 response in part two of M3.2 prepopulated_is_p_type_fifteen should be TRUE if participant is of p_code 15 type
     Failure/Error: let(:person) { Factory(:person) }
     RuntimeError:
       No values found for code list "COMMUNICATION_RANK_CL1"
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:54:in `code_list'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:149:in `validate_ncs_code_value'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:143:in `validate_ncs_code'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:104:in `block (2 levels) in build_extensions_module'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:22:in `block (3 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:43:in `block (4 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `call'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `block (3 levels) in <module:ResponseSetPrepopulation>'

  2) ResponseSetPrepopulation::PbsParticipantVerification for prepopulated P_TYPE 15 response in part two of M3.2 prepopulated_is_p_type_fifteen should be FALSE if participant is not of p_code 15 type
     Failure/Error: let(:person) { Factory(:person) }
     RuntimeError:
       No values found for code list "COMMUNICATION_RANK_CL1"
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:54:in `code_list'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:149:in `validate_ncs_code_value'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:143:in `validate_ncs_code'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:104:in `block (2 levels) in build_extensions_module'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:22:in `block (3 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:51:in `block (4 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `call'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `block (3 levels) in <module:ResponseSetPrepopulation>'

  3) ResponseSetPrepopulation::PbsParticipantVerification for prepopulated P_TYPE 15 response in part two of M3.2 prepopulated_is_p_type_fifteen should be TRUE if participant is a child and participant's mother has p_code 15
     Failure/Error: person_child = Factory(:person)
     RuntimeError:
       No values found for code list "COMMUNICATION_RANK_CL1"
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:54:in `code_list'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:149:in `validate_ncs_code_value'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:143:in `validate_ncs_code'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:104:in `block (2 levels) in build_extensions_module'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:60:in `block (4 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `call'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `block (3 levels) in <module:ResponseSetPrepopulation>'

  4) ResponseSetPrepopulation::PbsParticipantVerification for prepopulated P_TYPE 15 response in part two of M3.2 prepopulated_is_p_type_fifteen should be FALSE if participant is a child and participant's mother is not of p_code 15
     Failure/Error: person_child = Factory(:person)
     RuntimeError:
       No values found for code list "COMMUNICATION_RANK_CL1"
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:54:in `code_list'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:149:in `validate_ncs_code_value'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:143:in `validate_ncs_code'
     # ./lib/ncs_navigator/core/mdes/ncs_coded_attribute.rb:104:in `block (2 levels) in build_extensions_module'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:70:in `block (4 levels) in <module:ResponseSetPrepopulation>'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `call'
     # ./spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb:34:in `block (3 levels) in <module:ResponseSetPrepopulation>'
```

Still looking into it.

**Comment by rsutphin** [comment]
Further weirdness: after running once and failing, subsequent runs (on this PR's branch) work. This is repeatable:

1) `git checkout develop`
2) `bundle exec rspec spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb` — fails with `pg_restore: [archiver] unexpected end of file`.
3) `git checkout 4143-regen_mdes_codes`
4) `bundle exec rspec spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb` — fails with `No values found for code list "COMMUNICATION_RANK_CL1"`.
5) `bundle exec rspec spec/models/response_set_prepopulation/pbs_participant_verification_spec.rb` — passes.

If not for the mysterious (4), I would say that this indicates that we should merge this PR to address the CI problems. I have a vague sense that (4) is caused by the code list table being empty at some point and the tests seeing a different version of the table than is live in the database due to transaction isolation or something. But nothing I can fully explain.

**Comment by rsutphin** [comment]
The behavior in 4 & 5 of my previous comment also happens if you just delete the contents of the `ncs_codes` table by hand. This makes me think that this is a separate issue from the possibly-corrupt dumpfile problem.

**Comment by rsutphin** [comment]
The 4 & 5 weirdness was caused by a combination of [Cases-4176](https://code.bioinformatics.northwestern.edu/issues/issues/show/4176) and the problem fixed in 9d674a1bef2. We should be good to merge this PR now.

**Pull request merged**
