### PR TITLE
Prepopulation tasks

### PR DESCRIPTION
**Pull request by phebal**
Various pre-population tasks.  They're all bunched together in one branch because I didn't know to do one task per branch.  Most of the commits already got some review from David and Paul.  Merging with master will cause conflicts, I have a patch that would resolve them.

### CODE REVIEW

**Comment by rsutphin** [comment]
>  Merging with master will cause conflicts, I have a patch that would resolve them.

Please rebase onto master and resolve the conflicts then update the pull request. That will let us cleanly merge it once it's reviewed, and it will eliminate any possibility that the conflict-resolving patch would introduce problems that should have been caught during the review.

**Comment by phebal** [comment]
Sounds good but that will pull close to 300 other commits into the branch from master.  Is that ok?

**Comment by hannahwhy** [comment]
No, but that shouldn't be necessary.

**Comment by rsutphin** [comment]
> Sounds good but that will pull close to 300 other commits into the branch from master. Is that ok?

It won't — if you rebase, git will take the distinct commits in your branch and reapply them one at a time on top of the current master. When you force update the remote branch, the PR should reflect just the changes between your branch and master. So the other commits will be reflected in your branch, but they won't be part of your branch.

**Comment by phebal** [comment]
OK, got it, thank you both.

**Comment by phebal** [comment]
Rebased to master.

**Comment by phebal** [comment]
Reverted the latest commit and rebased onto master again per Paul's request.

**Pull request merged**
