### PR TITLE
New PSC scheduled activity report -> Cases entity mapping code

### PR DESCRIPTION
**Pull request by hannahwhy**
This pull request contains a redesign of the PSC scheduled activity report -> Cases entity mapping code.  The redesign maps rows in the scheduled activity report to Cases entities, building instruments, contacts, and contact links where appropriate, and saves generated entities.

I'd appreciate comments on whether or not the mapping is correct, as well as the usual comments re: code style, organization, etc.

The mapping is done in `#resolve_models`.  `#process` is a preprocessing step that merges rows into model placeholders.  (I suppose the former can be done from the latter.)

JSON generation for consumption by the field client is a separate task, but should fall out pretty easily from this code.  To associate events with contacts, for example, one could do this:

``` ruby

report.contacts.each do |c|
  events_for_contact = report.events.select { |e| e.contact == c }

  doc = {}

  doc['contact_id'] = c.model.public_id
  ...
  doc['events'] = events_for_contact.map do |e|
    { ... }
  end
end
```

A similar idea applies to event -> instrument association.

This technically has quadratic behavior wrt the number of iterations through `report.events`, but in practice I haven't noticed it being the bottleneck -- database activity tends to be the problem.  If it becomes a problem, we can preprocess the event lists for faster access.

### CODE REVIEW

**Comment by hannahwhy** [comment]
It may be helpful to see the code in action.  To do that, start a Rails console and run

``` ruby
json = JSON.parse(File.read('spec/models/psc/ex1.json'))
report = Psc::ScheduledActivityReport.from_json(json)
report.extend(Psc::ScheduledActivityReport::EntityMapping)

report.staff_id = '(whatever)'
report.process
report.resolve_models # etc.
```

You can inspect the state of the report at each (post-extend) step via `report.contacts`, `report.events`, etc.

**Comment by hannahwhy** [comment]
One other thing about running the code in a development environment: `ex1.json` references many entities, some of which may not exist.  The easiest way to get those entities to exist might be to invoke the `Factory` directives from the tests in your development environment.  @pfriedman may also have a suitable database dump.

**Comment by rsutphin** [comment]
This is a good idea, but I'd suggest that the boundary between the base `ScheduledActivityReport` and the `EntityMapping` should be moved. The potential participants, contacts, and events that an SA report describes are defined by the conventions that Cases uses (i.e., the use of `ideal_date` + event label to describe an event). The things that might change depending on what part of Cases is consuming the SA report are what to do with those potential domain elements. (Should they be resolved from the database? Should they be created if they don't exist? Are we just looking for counts?)

So, I'd suggest putting the mapping from PSC concepts to Cases concepts in the base `Psc::ScheduledActivityReport`. Have it generate intermediate descriptions of the concepts which can be consumed by collaborating classes. This will make the base unit reusable as well as limiting the number of places the concept mapping is implemented.

`PscParticipant` is an example of this pattern. It takes a participant's JSON schedule and maps SAs into implied events, represented by a documented hash structure. Collaborators (currently only the importer) can use this information to resolve to existing Cases events, create new ones, etc.

**Comment by hannahwhy** [comment]
I'll move `EntityMapping#process` to `Psc::ScheduledActivityReport`, and change `EntityMapping#process` to something like

``` ruby
def process
  super
  resolve_models
end
```

(or just merge `#resolve_models` into `#process`)

I was thinking about adopting `PscParticipant`'s event mapping code, but found it easier to deal with sets and value objects.  Nevertheless, there is some value in making `Psc::ScheduledActivityReport` and `PscParticipant` use the same intermediate representation of events (though I don't know how much); is it worth adding now?

**Comment by rsutphin** [comment]
> is it worth adding now?

I think it can wait until there's consuming code we want to share.

**Comment by hannahwhy** [comment]
I've moved the SA -> Cases IR mapping to `Psc::ScheduledActivityReport#process`.

**Comment by hannahwhy** [comment]
Merged.

**Pull request closed without merging**
