### PR TITLE
Derive instrument version from survey title

### PR DESCRIPTION
**Pull request by jdzak**
Instead of having Field and users set the instrument version we could derive it from survey title.

### CODE REVIEW

**Comment by hannahwhy** [comment]
I'm :+1: on this, having suggested it, and I think this solidifies the instrument-survey relationship.  (Also, if this pull request is making an incorrect assumption, at least it brings said assumption to light.)

**Comment by jdzak** [comment]
I changed this slightly. Now I'm leaving instrument_version on instrument in the database and the value is being set in a before_create hook if it doesn't already exist. This should allow the warehouse to pull the value from the database and it could still be updated in the UI if needed.

**Comment by hannahwhy** [comment]
Can you collapse the reversions into the previous commits?  It'll clean up the commit history.

**Comment by hannahwhy** [comment]
Also: making it a `before_create` hook is fine, but how about changes to `Instrument#survey_id` or `Survey#title`?  Are we going to say that they never change?

**Comment by jdzak** [comment]
@pfriedman Do you know if the survey_id on Instrument is static?

survey on Instrument is set once during person.build_instrument(survey) - I don't believe it is ever updated.

**Comment by hannahwhy** [comment]
> survey on Instrument is set once during person.build_instrument(survey) - I don't believe it is ever updated.

For now, yes.  What about future changes?

I ask this because code that keeps `instrument_version` in sync with survey title _and_ association changes is significantly more complex than a `before_create` hook.  I'd prefer that we not need that code; however, if we don't need it I'd like to know why.

AFAIK, surveys and instrument -> survey associations will never be mutated, so maybe that's the key.

**Comment by pfriedman** [comment]
I believe we can assume that this association will never change and we would not need to synchronize the instrument version and the survey association. 

I cannot imagine a scenario in which the survey association would ever change.

**Pull request merged**
