### PR TITLE
Update participant verification prepopulation

### PR DESCRIPTION
**Pull request by jdzak**
The participant verification instrument has been updated to match the MDES specification. Update the prepopulation to match the latest instrument.

### CODE REVIEW

**Comment by hannahwhy** [comment]
Why did you merge this?  This isn't part of the 1.8.0 release plan, or at least isn't officially in there.

**Comment by phebal** [comment]
John said he'd like to include it in 1.8.0 and he's the manger for this version of the release.  Let me know if I should undo.

**Comment by flockom** [comment]
That's fine, then, but #4196 is marked as belonging to 1.x, not 1.8.0.  If that's changed, then the corresponding issue has to also be changed.

**Comment by jdzak** [comment]
I told @phebal it was ok to merge. I realize this wasn't a part of the original release plan, but I thought it would be beneficial having this since it fixes a prepopulation participant verification issues and tranform issues related to participant verification.

**Pull request merged**
