### PR TITLE
Update existing core event's psc_ideal_date to the matched PSC event's ideal date.

### PR DESCRIPTION
**Pull request by jpatel**
Update the Operational Importer PSC Sync code to update the existing core events psc_ideal_date to match PSC event's ideal date for already scheduled segments.

### CODE REVIEW

**Comment by jpatel** [comment]
Ready for review again.

**Comment by jpatel** [comment]
@pfriedman - I am not sure whether you were looking at right commit. Can you please confirm you were looking right changes from file changed? I have addressed the @rsutphin comment in the line 103 to 113.

**Comment by pfriedman** [comment]
@jpatel Thanks for the clarification. I must've missed those.

**Comment by pfriedman** [comment]
@jpatel You could always update to `update_attributes!` on master at a later date. I'm sure that change will not require a PR.

**Pull request merged**
