### PR TITLE
Hotfix 1.7.1

### PR DESCRIPTION
**Pull request by jefflunt**
Added explanation of relationship code. New pull request - see: related:
https://github.com/NUBIC/ncs_navigator_core/pull/220

### CODE REVIEW

**Comment by phebal** [comment]
This looks good.  David do you feel that your concerns have been addressed?

**Comment by hannahwhy** [comment]
> This looks good. David do you feel that your concerns have been addressed?

Changes labeled "hotfixes" imply that they're short-cutting the QA process.  As such, it is very possible that a hotfix will cause more problems than it solves.  What I'm looking for are explanations for why that won't be true for this particular change.

I've one outstanding question in that regard.

**Comment by jefflunt** [comment]
It never occurred to me that a hotfix would circumvent QA. I have no
problem running it through QA.

**Comment by hannahwhy** [comment]
Cool, just checking.  I'm good with this.

**Comment by hannahwhy** [comment]
After this was merged, the build failed:

https://public-ci.nubic.northwestern.edu/job/NCS%20Navigator%20Core/CI_RUBY=1.9.3-p429/1814/consoleFull

The failure doesn't look related, but I want to make sure someone's looking at it.

**Comment by jefflunt** [comment]
Roger

**Comment by phebal** [comment]
Jenkins is now building master.  The successful builds prior to the failure David is referring to were of the develop branch.  Mater is at 1.7.x and lacks many if not all the fixes that made develop pass.

**Pull request merged**
