### PR TITLE
Feature 3790 psc registration processor

### PR DESCRIPTION
**Pull request by jpatel**
Add psc registration module which will take list of participant ids and will sync with PSC. This will be useful when import didn't register some participants for some reason.( e.g participant had all events with retired event type or particular segment is not available in PSC template)

### CODE REVIEW

**Comment by rsutphin** [comment]
PRs shouldn't include merges. Can you rebase over master to clear that out?

**Comment by jpatel** [comment]
Rebase the branch with correct changes. Ready for review.

**Comment by jpatel** [comment]
Ready for review again. Made changes based on comments.

**Comment by rsutphin** [comment]
Merged into develop.

**Comment by jpatel** [comment]
Just restore the branch to deploy on app server. Once working as expected, I'll delete the branch.

**Pull request closed without merging**
