### PR TITLE
Ensure that every test answer belongs to the test-corresponding question (#4181)

### PR DESCRIPTION
**Pull request by rsutphin**
See [Cases-4181](https://code.bioinformatics.northwestern.edu/issues/issues/show/4181) for motivation.

This was done by reviewing all uses of `Factory(:answer)`. This seems to cover the bulk of the CI failures caused by the underlying problem, but I haven't gone through all 100+ of them to verify that it covers them all.

When reviewing, please note the handful of occasions where more than just the test setup had to be modified. I'd appreciate review from the original authors of those tests to ensure that the tests were changed to test the wrong thing in these cases.

### CODE REVIEW

**Comment by hannahwhy** [comment]
The changes to `ResponseValue` and Field support-related bits look okay to me.

**Comment by hannahwhy** [comment]
That said, I don't see any changes where more than the test setup was changed.  Are there commits yet to be added to this PR?

**Comment by rsutphin** [comment]
> That said, I don't see any changes where more than the test setup was changed.

I guess there was only one: `spec/models/field/question_response_set_spec.rb`.

**Comment by jdzak** [comment]
Looks fine to me.

**Pull request merged**
